version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.RelationalSchema"
    - "src/Tests/Pure.RelationalSchema.Tests"
  schedule:
    interval: daily
  reviewers:
    - "kudima03"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
    - "kudima03"
